### ISSUE TITLE
Another host to block...

### ISSUE THREAD

**Issue by dadatti** [ignaciocastro/adobe-is-dumb#10]
![adobe 8 3 24](https://github.com/ignaciocastro/adobe-is-dumb/assets/162329832/9ba1fb68-27f9-46b7-a348-46038349ea39)

hi, today i saw antother host

do you know a other solution to get rid of this anoying popup?
looking every day for new hosts to block  is very time consuming...

**Comment by ignaciocastro** [comment]
**❓ Question** I can see that you're not blocking _ic.adobe.io_, which is generating the pop-up (see the part doing integrity checking). Please re-check your hosts file or your automatic update solution, because that domain is added to the list and your program shouldn't be able to communicate to it.

**Comment by ignaciocastro** [comment]
Closed due to inactivity.
