### ISSUE TITLE
Been getting the popup again!

### ISSUE THREAD

**Issue by contrivances** [ignaciocastro/adobe-is-dumb#3]
Hello, I saw that the last update was about two months ago and I've been having the popup again. Please help!

**Comment by ignaciocastro** [comment]
Hello, @contrivances. I have checked and I'm not getting any popup with the latest update. 

- Which program are you running, which version, which method for the blocklist are you using?
- Can you check whether your list is completely updated? Can you check whether you can load [this URL](https://5zgzzv92gn.adobe.io/)? You should get a browser error. If you see "404 Not Found", your list is not currently active.
- Lastly, if nothing works, could you please install Fiddler Classic ([Webpage](https://www.telerik.com/download/fiddler) or [Direct link](https://telerik-fiddler.s3.amazonaws.com/fiddler/FiddlerSetup.exe)), open it, open your Adobe app and take a screenshot of the requests once you get the pop-up? [Should look something like this](https://i.imgur.com/iNTpiWn.png) (Make sure you screenshot the adobe requests).

Thank you for your help!

PS: Remember that the last update does not represent the effectiveness of this blocklist, you can read more about it [here](https://github.com/ignaciocastro/adobe-is-dumb?tab=readme-ov-file#its-been-x-hoursdaysweeksmonths-since-this-last-updated-is-this-list-deprecated--abandoned)

**Comment by ignaciocastro** [comment]
**❌ Closed after 7 days of inacticity.**
